// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: protobuf/Message.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SKBuiltinString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Str *string `protobuf:"bytes,1,opt,name=str" json:"str,omitempty"`
}

func (x *SKBuiltinString) Reset() {
	*x = SKBuiltinString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_Message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SKBuiltinString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SKBuiltinString) ProtoMessage() {}

func (x *SKBuiltinString) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_Message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SKBuiltinString.ProtoReflect.Descriptor instead.
func (*SKBuiltinString) Descriptor() ([]byte, []int) {
	return file_protobuf_Message_proto_rawDescGZIP(), []int{0}
}

func (x *SKBuiltinString) GetStr() string {
	if x != nil && x.Str != nil {
		return *x.Str
	}
	return ""
}

type SKBuiltinBuffer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Len    *uint32 `protobuf:"varint,1,req,name=len" json:"len,omitempty"`
	Buffer []byte  `protobuf:"bytes,2,opt,name=buffer" json:"buffer,omitempty"`
}

func (x *SKBuiltinBuffer) Reset() {
	*x = SKBuiltinBuffer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_Message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SKBuiltinBuffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SKBuiltinBuffer) ProtoMessage() {}

func (x *SKBuiltinBuffer) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_Message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SKBuiltinBuffer.ProtoReflect.Descriptor instead.
func (*SKBuiltinBuffer) Descriptor() ([]byte, []int) {
	return file_protobuf_Message_proto_rawDescGZIP(), []int{1}
}

func (x *SKBuiltinBuffer) GetLen() uint32 {
	if x != nil && x.Len != nil {
		return *x.Len
	}
	return 0
}

func (x *SKBuiltinBuffer) GetBuffer() []byte {
	if x != nil {
		return x.Buffer
	}
	return nil
}

type SKBuiltinUint32 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UiVal *uint32 `protobuf:"varint,1,req,name=uiVal" json:"uiVal,omitempty"`
}

func (x *SKBuiltinUint32) Reset() {
	*x = SKBuiltinUint32{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_Message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SKBuiltinUint32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SKBuiltinUint32) ProtoMessage() {}

func (x *SKBuiltinUint32) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_Message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SKBuiltinUint32.ProtoReflect.Descriptor instead.
func (*SKBuiltinUint32) Descriptor() ([]byte, []int) {
	return file_protobuf_Message_proto_rawDescGZIP(), []int{2}
}

func (x *SKBuiltinUint32) GetUiVal() uint32 {
	if x != nil && x.UiVal != nil {
		return *x.UiVal
	}
	return 0
}

type BakChatMsgItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type              *uint32            `protobuf:"varint,1,req,name=type" json:"type,omitempty"`
	ClientMsgId       *string            `protobuf:"bytes,2,opt,name=clientMsgId" json:"clientMsgId,omitempty"`
	FromUserName      *SKBuiltinString   `protobuf:"bytes,3,req,name=fromUserName" json:"fromUserName,omitempty"`
	ToUserName        *SKBuiltinString   `protobuf:"bytes,4,req,name=toUserName" json:"toUserName,omitempty"`
	Content           *SKBuiltinString   `protobuf:"bytes,5,req,name=content" json:"content,omitempty"`
	MsgStatus         *uint32            `protobuf:"varint,6,req,name=msgStatus" json:"msgStatus,omitempty"`
	ClientMsgTime     *uint32            `protobuf:"varint,7,req,name=clientMsgTime" json:"clientMsgTime,omitempty"`
	MsgSource         *string            `protobuf:"bytes,8,req,name=msgSource" json:"msgSource,omitempty"`
	MsgId             *uint32            `protobuf:"varint,9,req,name=msgId" json:"msgId,omitempty"`
	MediaIdCount      *uint32            `protobuf:"varint,10,opt,name=mediaIdCount" json:"mediaIdCount,omitempty"`
	MediaId           []*SKBuiltinString `protobuf:"bytes,11,rep,name=mediaId" json:"mediaId,omitempty"`
	MediaType         []*SKBuiltinUint32 `protobuf:"bytes,12,rep,name=mediaType" json:"mediaType,omitempty"`
	Buffer            *SKBuiltinBuffer   `protobuf:"bytes,13,opt,name=buffer" json:"buffer,omitempty"`
	BufferLength      *uint32            `protobuf:"varint,14,opt,name=bufferLength" json:"bufferLength,omitempty"`
	BufferType        *uint32            `protobuf:"varint,15,opt,name=bufferType" json:"bufferType,omitempty"`
	NewMsgId          *uint64            `protobuf:"varint,16,opt,name=newMsgId" json:"newMsgId,omitempty"`
	SequentId         *uint32            `protobuf:"varint,17,opt,name=sequentId" json:"sequentId,omitempty"`
	ClientMsgMillTime *int64             `protobuf:"varint,18,opt,name=clientMsgMillTime" json:"clientMsgMillTime,omitempty"`
	MsgFlag           *uint32            `protobuf:"varint,19,opt,name=msgFlag" json:"msgFlag,omitempty"`
}

func (x *BakChatMsgItem) Reset() {
	*x = BakChatMsgItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_Message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BakChatMsgItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BakChatMsgItem) ProtoMessage() {}

func (x *BakChatMsgItem) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_Message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BakChatMsgItem.ProtoReflect.Descriptor instead.
func (*BakChatMsgItem) Descriptor() ([]byte, []int) {
	return file_protobuf_Message_proto_rawDescGZIP(), []int{3}
}

func (x *BakChatMsgItem) GetType() uint32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *BakChatMsgItem) GetClientMsgId() string {
	if x != nil && x.ClientMsgId != nil {
		return *x.ClientMsgId
	}
	return ""
}

func (x *BakChatMsgItem) GetFromUserName() *SKBuiltinString {
	if x != nil {
		return x.FromUserName
	}
	return nil
}

func (x *BakChatMsgItem) GetToUserName() *SKBuiltinString {
	if x != nil {
		return x.ToUserName
	}
	return nil
}

func (x *BakChatMsgItem) GetContent() *SKBuiltinString {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *BakChatMsgItem) GetMsgStatus() uint32 {
	if x != nil && x.MsgStatus != nil {
		return *x.MsgStatus
	}
	return 0
}

func (x *BakChatMsgItem) GetClientMsgTime() uint32 {
	if x != nil && x.ClientMsgTime != nil {
		return *x.ClientMsgTime
	}
	return 0
}

func (x *BakChatMsgItem) GetMsgSource() string {
	if x != nil && x.MsgSource != nil {
		return *x.MsgSource
	}
	return ""
}

func (x *BakChatMsgItem) GetMsgId() uint32 {
	if x != nil && x.MsgId != nil {
		return *x.MsgId
	}
	return 0
}

func (x *BakChatMsgItem) GetMediaIdCount() uint32 {
	if x != nil && x.MediaIdCount != nil {
		return *x.MediaIdCount
	}
	return 0
}

func (x *BakChatMsgItem) GetMediaId() []*SKBuiltinString {
	if x != nil {
		return x.MediaId
	}
	return nil
}

func (x *BakChatMsgItem) GetMediaType() []*SKBuiltinUint32 {
	if x != nil {
		return x.MediaType
	}
	return nil
}

func (x *BakChatMsgItem) GetBuffer() *SKBuiltinBuffer {
	if x != nil {
		return x.Buffer
	}
	return nil
}

func (x *BakChatMsgItem) GetBufferLength() uint32 {
	if x != nil && x.BufferLength != nil {
		return *x.BufferLength
	}
	return 0
}

func (x *BakChatMsgItem) GetBufferType() uint32 {
	if x != nil && x.BufferType != nil {
		return *x.BufferType
	}
	return 0
}

func (x *BakChatMsgItem) GetNewMsgId() uint64 {
	if x != nil && x.NewMsgId != nil {
		return *x.NewMsgId
	}
	return 0
}

func (x *BakChatMsgItem) GetSequentId() uint32 {
	if x != nil && x.SequentId != nil {
		return *x.SequentId
	}
	return 0
}

func (x *BakChatMsgItem) GetClientMsgMillTime() int64 {
	if x != nil && x.ClientMsgMillTime != nil {
		return *x.ClientMsgMillTime
	}
	return 0
}

func (x *BakChatMsgItem) GetMsgFlag() uint32 {
	if x != nil && x.MsgFlag != nil {
		return *x.MsgFlag
	}
	return 0
}

type BakChatMsgList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count *uint32           `protobuf:"varint,1,req,name=count" json:"count,omitempty"`
	List  []*BakChatMsgItem `protobuf:"bytes,2,rep,name=list" json:"list,omitempty"`
}

func (x *BakChatMsgList) Reset() {
	*x = BakChatMsgList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_Message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BakChatMsgList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BakChatMsgList) ProtoMessage() {}

func (x *BakChatMsgList) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_Message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BakChatMsgList.ProtoReflect.Descriptor instead.
func (*BakChatMsgList) Descriptor() ([]byte, []int) {
	return file_protobuf_Message_proto_rawDescGZIP(), []int{4}
}

func (x *BakChatMsgList) GetCount() uint32 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

func (x *BakChatMsgList) GetList() []*BakChatMsgItem {
	if x != nil {
		return x.List
	}
	return nil
}

var File_protobuf_Message_proto protoreflect.FileDescriptor

var file_protobuf_Message_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x22, 0x23, 0x0a, 0x0f, 0x53, 0x4b, 0x42, 0x75, 0x69, 0x6c, 0x74, 0x69, 0x6e, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x74, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x73, 0x74, 0x72, 0x22, 0x3b, 0x0a, 0x0f, 0x53, 0x4b, 0x42, 0x75, 0x69,
	0x6c, 0x74, 0x69, 0x6e, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x65,
	0x6e, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x03, 0x6c, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06,
	0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x62, 0x75,
	0x66, 0x66, 0x65, 0x72, 0x22, 0x27, 0x0a, 0x0f, 0x53, 0x4b, 0x42, 0x75, 0x69, 0x6c, 0x74, 0x69,
	0x6e, 0x55, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x69, 0x56, 0x61, 0x6c,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x05, 0x75, 0x69, 0x56, 0x61, 0x6c, 0x22, 0xf8, 0x05,
	0x0a, 0x0e, 0x42, 0x61, 0x6b, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x73, 0x67, 0x49, 0x74, 0x65, 0x6d,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x73,
	0x67, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x3d, 0x0a, 0x0c, 0x66, 0x72, 0x6f, 0x6d, 0x55, 0x73,
	0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x4b, 0x42, 0x75, 0x69, 0x6c, 0x74, 0x69,
	0x6e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x0c, 0x66, 0x72, 0x6f, 0x6d, 0x55, 0x73, 0x65,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x74, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x4b, 0x42, 0x75, 0x69, 0x6c, 0x74, 0x69, 0x6e, 0x53, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x52, 0x0a, 0x74, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x33, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x02, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x4b, 0x42,
	0x75, 0x69, 0x6c, 0x74, 0x69, 0x6e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x73, 0x67, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x06, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x09, 0x6d, 0x73, 0x67, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x73, 0x67,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x0d, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x4d, 0x73, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x73, 0x67,
	0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x08, 0x20, 0x02, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x73,
	0x67, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64,
	0x18, 0x09, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x22, 0x0a,
	0x0c, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x49, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0c, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x49, 0x64, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x33, 0x0a, 0x07, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x49, 0x64, 0x18, 0x0b, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x4b,
	0x42, 0x75, 0x69, 0x6c, 0x74, 0x69, 0x6e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x07, 0x6d,
	0x65, 0x64, 0x69, 0x61, 0x49, 0x64, 0x12, 0x37, 0x0a, 0x09, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x4b, 0x42, 0x75, 0x69, 0x6c, 0x74, 0x69, 0x6e, 0x55, 0x69,
	0x6e, 0x74, 0x33, 0x32, 0x52, 0x09, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x31, 0x0a, 0x06, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x4b, 0x42, 0x75, 0x69,
	0x6c, 0x74, 0x69, 0x6e, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x52, 0x06, 0x62, 0x75, 0x66, 0x66,
	0x65, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x4c, 0x65, 0x6e, 0x67,
	0x74, 0x68, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72,
	0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x62, 0x75, 0x66, 0x66,
	0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x65, 0x77, 0x4d, 0x73, 0x67,
	0x49, 0x64, 0x18, 0x10, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x6e, 0x65, 0x77, 0x4d, 0x73, 0x67,
	0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18,
	0x11, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x12, 0x2c, 0x0a, 0x11, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x73, 0x67, 0x4d, 0x69, 0x6c,
	0x6c, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x12, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x4d, 0x73, 0x67, 0x4d, 0x69, 0x6c, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x73, 0x67, 0x46, 0x6c, 0x61, 0x67, 0x18, 0x13, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x07, 0x6d, 0x73, 0x67, 0x46, 0x6c, 0x61, 0x67, 0x22, 0x54, 0x0a, 0x0e, 0x42, 0x61, 0x6b, 0x43,
	0x68, 0x61, 0x74, 0x4d, 0x73, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x2c, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x61, 0x6b, 0x43, 0x68, 0x61,
	0x74, 0x4d, 0x73, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x42, 0x2f,
	0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6e, 0x6f,
	0x6e, 0x79, 0x6d, 0x6f, 0x75, 0x73, 0x35, 0x6c, 0x2f, 0x77, 0x63, 0x64, 0x62, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
}

var (
	file_protobuf_Message_proto_rawDescOnce sync.Once
	file_protobuf_Message_proto_rawDescData = file_protobuf_Message_proto_rawDesc
)

func file_protobuf_Message_proto_rawDescGZIP() []byte {
	file_protobuf_Message_proto_rawDescOnce.Do(func() {
		file_protobuf_Message_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_Message_proto_rawDescData)
	})
	return file_protobuf_Message_proto_rawDescData
}

var file_protobuf_Message_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_protobuf_Message_proto_goTypes = []interface{}{
	(*SKBuiltinString)(nil), // 0: protobuf.SKBuiltinString
	(*SKBuiltinBuffer)(nil), // 1: protobuf.SKBuiltinBuffer
	(*SKBuiltinUint32)(nil), // 2: protobuf.SKBuiltinUint32
	(*BakChatMsgItem)(nil),  // 3: protobuf.BakChatMsgItem
	(*BakChatMsgList)(nil),  // 4: protobuf.BakChatMsgList
}
var file_protobuf_Message_proto_depIdxs = []int32{
	0, // 0: protobuf.BakChatMsgItem.fromUserName:type_name -> protobuf.SKBuiltinString
	0, // 1: protobuf.BakChatMsgItem.toUserName:type_name -> protobuf.SKBuiltinString
	0, // 2: protobuf.BakChatMsgItem.content:type_name -> protobuf.SKBuiltinString
	0, // 3: protobuf.BakChatMsgItem.mediaId:type_name -> protobuf.SKBuiltinString
	2, // 4: protobuf.BakChatMsgItem.mediaType:type_name -> protobuf.SKBuiltinUint32
	1, // 5: protobuf.BakChatMsgItem.buffer:type_name -> protobuf.SKBuiltinBuffer
	3, // 6: protobuf.BakChatMsgList.list:type_name -> protobuf.BakChatMsgItem
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_protobuf_Message_proto_init() }
func file_protobuf_Message_proto_init() {
	if File_protobuf_Message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_Message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SKBuiltinString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_Message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SKBuiltinBuffer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_Message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SKBuiltinUint32); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_Message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BakChatMsgItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_Message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BakChatMsgList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_Message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_Message_proto_goTypes,
		DependencyIndexes: file_protobuf_Message_proto_depIdxs,
		MessageInfos:      file_protobuf_Message_proto_msgTypes,
	}.Build()
	File_protobuf_Message_proto = out.File
	file_protobuf_Message_proto_rawDesc = nil
	file_protobuf_Message_proto_goTypes = nil
	file_protobuf_Message_proto_depIdxs = nil
}
